# Calculate confidence intervals

In [31]:
import numpy as np 
from scipy.stats import t

In [33]:
x = np.random.normal(size=100)

In [32]:
m = x.mean() 
s = x.std() 
dof = len(x)-1 
confidence = 0.95

NameError: name 'x' is not defined

In [4]:
s3

[(0, 0, 0),
 (0, 0, 1),
 (0, 1, 0),
 (0, 1, 1),
 (1, 0, 0),
 (1, 0, 1),
 (1, 1, 0),
 (1, 1, 1)]

In [5]:
# step = 1/6
I = list(range(0,7,1))
I = [i/6 for i in I]
P = I
E = list(range(0,11,1))
E = [i/10 for i in E]
E

[0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]

In [6]:
dict_I = dict(zip(l1,I))
dict_P = dict_I
dict_E = dict(zip(l3,E))
dict_E

{(0, 0, 0, 0): 0.0,
 (0, 0, 0, 1): 0.1,
 (0, 0, 1, 0): 0.2,
 (0, 0, 1, 1): 0.3,
 (0, 1, 0, 0): 0.4,
 (0, 1, 0, 1): 0.5,
 (0, 1, 1, 0): 0.6,
 (1, 0, 0, 0): 0.7,
 (1, 0, 0, 1): 0.8,
 (1, 0, 1, 0): 0.9,
 (1, 1, 0, 0): 1.0}

In [7]:
inputs_d = []
k=0
for i in inputs:
    t = [dict_I[i[0]], dict_P[i[1]], dict_E[i[2]]]
    inputs_d.append(t)
inputs_d

[[0.0, 0.0, 0.0],
 [0.0, 0.0, 0.1],
 [0.0, 0.0, 0.2],
 [0.0, 0.0, 0.3],
 [0.0, 0.0, 0.4],
 [0.0, 0.0, 0.5],
 [0.0, 0.0, 0.6],
 [0.0, 0.0, 0.7],
 [0.0, 0.0, 0.8],
 [0.0, 0.0, 0.9],
 [0.0, 0.0, 1.0],
 [0.0, 0.16666666666666666, 0.0],
 [0.0, 0.16666666666666666, 0.1],
 [0.0, 0.16666666666666666, 0.2],
 [0.0, 0.16666666666666666, 0.3],
 [0.0, 0.16666666666666666, 0.4],
 [0.0, 0.16666666666666666, 0.5],
 [0.0, 0.16666666666666666, 0.6],
 [0.0, 0.16666666666666666, 0.7],
 [0.0, 0.16666666666666666, 0.8],
 [0.0, 0.16666666666666666, 0.9],
 [0.0, 0.16666666666666666, 1.0],
 [0.0, 0.3333333333333333, 0.0],
 [0.0, 0.3333333333333333, 0.1],
 [0.0, 0.3333333333333333, 0.2],
 [0.0, 0.3333333333333333, 0.3],
 [0.0, 0.3333333333333333, 0.4],
 [0.0, 0.3333333333333333, 0.5],
 [0.0, 0.3333333333333333, 0.6],
 [0.0, 0.3333333333333333, 0.7],
 [0.0, 0.3333333333333333, 0.8],
 [0.0, 0.3333333333333333, 0.9],
 [0.0, 0.3333333333333333, 1.0],
 [0.0, 0.5, 0.0],
 [0.0, 0.5, 0.1],
 [0.0, 0.5, 0.2],
 [0.0, 0.5,

### Sampling
### Variance decomposition
We see this model as a function $f(X)=Y$, where the inputs are the scenarios, so $X\in\mathbb{R}^d$ and the output is a real value, that in our case, can be the emissions or the mobility choices. First, we are going to do an analysis on (overall) emissions and when we implement it, we can use the othe outputs.

The idea consists in estimating certain variances that we are going to define later in order to compute some sesitivity indices (there are first and second order sensitivity indices). We write
$$Var(Y)=\sum_{i=1}^dV_i+\sum_{i<j}^dV_{ij}+\ldots+V_{1,2, \ldots,d}$$where
$$V_i=Var_{x_i}(E_{X_{\sim i}}(Y|X))$$where the $X_{\sim i}$ notation means the set of all variables except $x_i$.

#### First Order Index
$$S_i= \frac{V_i}{Var(Y)}$$We can interpret it as follows: "the fractional reduction in the variance of $Y$ which would be obtained on average if $X$ could be fixed".


In [8]:
def sampling(in_space,N):
    AB = random.sample(in_space,2*N)
    A = AB[0:N]
    B = AB[N:2*N]
    return A,B

In [9]:
ABtest = random.sample(inputs_d,2*8)
Atest = ABtest[0:8]
Btest = ABtest[8:16]
Atest
ABtest = np.zeros((3,8,3))
Ant,Bnt = np.array(Atest), np.array(Btest)
ABtest[0] = Ant
ABtest[0][:,0] = Bnt[:,0]
ABtest[1]
dict_I

{(0, 0, 0): 0.0,
 (0, 0, 1): 0.16666666666666666,
 (0, 1, 0): 0.3333333333333333,
 (0, 1, 1): 0.5,
 (1, 0, 0): 0.6666666666666666,
 (1, 0, 1): 0.8333333333333334,
 (1, 1, 0): 1.0}

In [10]:
def mat_AB_i(A,B): 
    d = 3
    N = len(A)
    An,Bn = np.array(A), np.array(B)
    AB_mat = np.zeros((d,N,d))
    for i in range(0,d):
        AB_mat[i] = An
        AB_mat[i][:,i] = Bn[:,i]
    return AB_mat

In [11]:
ABi = mat_AB_i(Atest,Btest)
ABi

array([[[0.        , 1.        , 0.1       ],
        [0.5       , 0.        , 0.8       ],
        [0.33333333, 0.33333333, 1.        ],
        [0.5       , 0.5       , 0.6       ],
        [0.16666667, 0.5       , 0.7       ],
        [0.83333333, 0.66666667, 0.6       ],
        [0.16666667, 0.66666667, 0.1       ],
        [0.66666667, 0.66666667, 0.9       ]],

       [[0.33333333, 0.5       , 0.1       ],
        [1.        , 0.        , 0.8       ],
        [0.83333333, 0.33333333, 1.        ],
        [0.16666667, 0.83333333, 0.6       ],
        [0.33333333, 1.        , 0.7       ],
        [1.        , 0.16666667, 0.6       ],
        [0.33333333, 0.66666667, 0.1       ],
        [0.        , 0.        , 0.9       ]],

       [[0.33333333, 1.        , 0.2       ],
        [1.        , 0.        , 0.7       ],
        [0.83333333, 0.33333333, 0.        ],
        [0.16666667, 0.5       , 0.3       ],
        [0.33333333, 0.5       , 0.6       ],
        [1.        , 0.6666666

### Estimating
To compute the variance, we can use the following estimator: $$Var_{x_i}(E_{X_{\sim i}}(Y|X))\approx \frac{1}{N}\sum_{i=1}^Nf(B)_j\left(f(A_B^i)_j-f(A)_j\right)$$

First, get outputs and then compute the variance

In [12]:
te_df = pd.read_csv("total_emissions.csv") # global variable
te_df
cond = (te_df['scenario'] == "CH0SP0SE0WE0BP1RE1CO1DI1WO0CS0")
result = te_df[cond].total_emissions.values[0]
result

2164500073013.347

In [13]:
def invert_dict(d_X):
    dI_X = {v: k for k, v in d_X.items()}
    return dI_X
d_I = invert_dict(dict_I)
d_P = invert_dict(dict_P)
d_E = invert_dict(dict_E)

In [14]:
d_I[0.5]

(0, 1, 1)

In [15]:
def from_dec_to_bool(row):
    rbool = [d_I[row[0]], d_P[row[1]], d_E[row[2]]]
    return rbool

In [16]:
from_dec_to_bool(ABi[0][0])

[(0, 0, 0), (1, 1, 0), (0, 0, 0, 1)]

In [17]:
# input is a list of tuples [(1,0,0),(0,1,0),(1,0,0,0)]
# output 'CH1SP0SE0WE0BP1RE0CO1DI0WO0CS0'
def get_scenario_string(boolean_scenario): 
    bool_sc = list(sum(boolean_scenario,())) # flatten list
    dict2_I = dict(zip(I,l1))
    dict2_P = dict_I
    dict2_E = dict(zip(E,l3))
    #dict_E
    list_events = ['CH','SP','SE','WE','BP','RE','CO','DI','WO','CS']
    # prefix = "timeSeries_"
    # sufix = ".csv"
    f_n = [l+str(s) for l,s in zip(list_events,bool_sc)]
    f_n = ''.join(f_n)
    file_name = f_n
    return file_name

In [18]:
ABi[0][0]

array([0. , 1. , 0.1])

In [19]:
get_scenario_string(from_dec_to_bool(ABi[0][0]))

'CH0SP0SE0WE1BP1RE0CO0DI0WO0CS1'

In [20]:
def get_output(M):#input is a matrix M, make sure it is a list
    out_vector = []
    n = len(M)
    for i in range(0,n):
        dec_row = M[i]
        row_bool = from_dec_to_bool(dec_row)
        string = get_scenario_string(row_bool)
        cond = (te_df['scenario'] == string)
        # print(cond)
        outp = te_df[cond].total_emissions.values[0]
        out_vector.append(outp)
    return out_vector

In [21]:
Atest

[[0.3333333333333333, 1.0, 0.1],
 [1.0, 0.0, 0.8],
 [0.8333333333333334, 0.3333333333333333, 1.0],
 [0.16666666666666666, 0.5, 0.6],
 [0.3333333333333333, 0.5, 0.7],
 [1.0, 0.6666666666666666, 0.6],
 [0.3333333333333333, 0.6666666666666666, 0.1],
 [0.0, 0.6666666666666666, 0.9]]

In [22]:
ABi

array([[[0.        , 1.        , 0.1       ],
        [0.5       , 0.        , 0.8       ],
        [0.33333333, 0.33333333, 1.        ],
        [0.5       , 0.5       , 0.6       ],
        [0.16666667, 0.5       , 0.7       ],
        [0.83333333, 0.66666667, 0.6       ],
        [0.16666667, 0.66666667, 0.1       ],
        [0.66666667, 0.66666667, 0.9       ]],

       [[0.33333333, 0.5       , 0.1       ],
        [1.        , 0.        , 0.8       ],
        [0.83333333, 0.33333333, 1.        ],
        [0.16666667, 0.83333333, 0.6       ],
        [0.33333333, 1.        , 0.7       ],
        [1.        , 0.16666667, 0.6       ],
        [0.33333333, 0.66666667, 0.1       ],
        [0.        , 0.        , 0.9       ]],

       [[0.33333333, 1.        , 0.2       ],
        [1.        , 0.        , 0.7       ],
        [0.83333333, 0.33333333, 0.        ],
        [0.16666667, 0.5       , 0.3       ],
        [0.33333333, 0.5       , 0.6       ],
        [1.        , 0.6666666

In [23]:
# this function takes as input the matrices A and B
# and the original matrix ABi. 
# the index i at the end is the variable name, it can be 0, 1 or 2
def get_var_xi(A,B,ABi,i):
    ABi = ABi[i].tolist() # add '.astype(int)' in the middle if there are any probs with type
    out_A = get_output(A)
    out_B = get_output(B)
    out_ABi = get_output(ABi)    
    N = len(A)
    var = 0
    for j in range(0,N):
        var = out_B[j]*(out_ABi[j]-out_A[j])+var
    var = var/N
    return var

In [24]:
varI = get_var_xi(Atest,Btest,ABi,0)
varI

-3.338574080194094e+20

In [25]:
varP = get_var_xi(Atest,Btest,ABi,1)
varP

4.000829683077316e+22

In [26]:
varE = get_var_xi(Atest,Btest,ABi,2)
varE

1.5925644336074813e+22

In [27]:
# overall variance
varY = te_df['total_emissions'].var(axis=0)
varY
# te_df['total_emissions']

4.3590406163040557e+21

## Computing sensitivity indices

In [28]:
S_I = varI / varY
S_P = varP / varY
S_E = varE / varY


In [30]:
print(f'- The sensitivity of the Investment category is {str(S_I)},\n- The sensitivity of the Policy category is {str(S_P)},\n- The sensitivity of the Events category is {str(S_E)}')

- The sensitivity of the Investment category is -0.0765896529549845,
- The sensitivity of the Policy category is 9.178234467724552,
- The sensitivity of the Events category is 3.653474637632042
